name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 获取仓库文件
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: 安装 JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 使用 Gradle 构建
        run: ./gradlew build

      - name: 上传 Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: neomafishmod-snapshot
          path: build/libs/*.jar
